[package]
name = "shush"
version = "0.1.0"
authors = ["John Baublitz <john.baublitz@threatstack.com>"]

[dependencies]
futures = "0.1.16"
regex = "0.2.1"
tokio-core = "0.1.9"
hyper = "0.11.2"
hyper-tls = "0.1.2"
native-tls = "0.1.4"
serde_json = "1.0.0"
getopts = "0.2.14"
itertools = "0.6.0"
rust-ini = "0.10.0"
